export const DEFAULT_CONNECT_TIMEOUT_MS = 2_000;
export const DEFAULT_WAIT_REMINDER_MS = 60_000;
export const DEFAULT_WAIT_EXPIRY_MS = 120_000;
export const DEFAULT_RESPONSE_TIMEOUT_MS = 125_000;
export const DEFAULT_MAX_MESSAGE_BYTES = 1_048_576;

export const CONTINUATION_MARKER = "BLABEE_M0_CONTINUATION_V1";
