export const COPY = {
    "a11y.skip": "Skip to content",
    "header.cta": "Mac beta",

    "hero.eyebrow": "FOR CODEX · macOS",
    "hero.headline1": "One small decision.",
    "hero.headline2": "Don’t go back to the terminal.",
    "hero.description": "When Codex has useful next actions, Blabee surfaces them on your Mac. Respond with one shortcut—without breaking your flow.",
    "hero.cta": "Join the Mac beta ↗",
    "hero.betaNote": "macOS · Private beta",
    "hero.demoCaption": "One shortcut. Same session. Keep going.",

    "demo.workingPrompt": "Implement email login with secure sessions",
    "demo.workingLog1": "✓ Read app/api/auth/login/route.ts",
    "demo.workingLog2": "✓ Edited lib/auth/session.ts",
    "demo.workingLog3": "→ pnpm test -- auth",
    "demo.workingStatus": "Running 12 auth tests",
    "demo.completedLog1": "✓ Edited app/api/auth/login/route.ts",
    "demo.completedLog2": "✓ Added lib/auth/session.ts",
    "demo.completedLog3": "✓ pnpm test -- auth · 12/12 passed",
    "demo.completedStatus": "Done · 2 files changed · 12 tests passed",
    "demo.choice1": "Implement logout",
    "demo.fromCodex": "From Codex",
    "demo.choice2": "Review auth architecture",
    "demo.choice3": "Add session rotation tests",
    "demo.choice4": "Inspect auth edge cases",
    "demo.reviewPrompt": "Review the auth flow for security boundaries",
    "demo.reviewLog1": "✓ Read middleware.ts",
    "demo.reviewLog2": "✓ Traced lib/auth/session.ts",
    "demo.reviewLog3": "⚠ Session cookie rotation is missing",
    "demo.reviewStatus": "Checking cookie and expiry edge cases",
    "demo.viewDetails": "View details",
    "demo.choicesLabel": "Blabee choices",

    "benefits.eyebrow": "FOR THE LONG RUN",
    "benefits.headline1": "Codex keeps working.",
    "benefits.headline2": "So can you.",
    "benefits.intro": "Built for people who hand off a task, move to another window, and do not want to keep watching the terminal.",
    "benefits.item1Title": "Keep your flow in another window",
    "benefits.item1Body": "Stay in your browser or document without checking the Codex screen over and over.",
    "benefits.item2Title": "Look only when it matters",
    "benefits.item2Body": "Blabee appears quietly when Codex has useful next actions for you.",
    "benefits.item3Title": "See the next actions, not a long reply",
    "benefits.item3Body": "Choose quickly from up to four next actions Codex provides.",

    "how.eyebrow": "HOW IT WORKS",
    "how.headline": "Three steps. Then work moves again.",
    "how.intro": "Blabee does not decide for you. It surfaces Codex’s next actions and keeps your choice in the same session.",
    "how.step1Title": "Codex has useful next actions",
    "how.step1Body": "Codex prepares two to four genuine ways to continue the current work.",
    "how.step2Title": "Blabee surfaces the ranked actions",
    "how.step2Body": "Review the next actions Codex prepared and choose with your configured shortcut.",
    "how.step3Title": "The same session continues",
    "how.step3Body": "Your choice becomes a new user turn in the original Codex session.",

    "scope.eyebrow": "CURRENT PRIVATE BETA",
    "scope.headline": "What we are testing now",
    "scope.intro": "We are validating the core loop with a small group before a public download.",
    "scope.label1": "SUPPORT",
    "scope.value1": "Codex · macOS",
    "scope.label2": "CORE LOOP",
    "scope.value2": "Surface choices · choose with a shortcut · continue in the same session",
    "scope.label3": "ACCESS",
    "scope.value3": "Private installation guidance for selected users",

    "faq.eyebrow": "FAQ",
    "faq.headline": "A few things worth knowing",
    "faq.intro": "Straight answers based on the current private beta.",
    "faq.q1": "Does Blabee create the next actions?",
    "faq.a1": "No. Codex creates the choices. Blabee surfaces them and sends your selection back to the original session.",
    "faq.q2": "Does it open a new Codex session?",
    "faq.a2": "No. Your selection is delivered as a new user turn in the original Codex session.",
    "faq.q3": "Does Blabee appear after every Codex response?",
    "faq.a3": "No. It appears only when Codex has useful next actions for the current response and the current session is correctly bound.",
    "faq.q4": "Does the beta support Claude Code?",
    "faq.a4": "The current private beta is Codex-first. Support for other agents is not confirmed yet.",
    "faq.q5": "Do I need another AI API key?",
    "faq.a5": "No. Blabee does not add a separate LLM API key or inference service.",

    "signup.eyebrow": "PRIVATE BETA FOR MAC",
    "signup.headline1": "Decide fast.",
    "signup.headline2": "Keep building.",
    "signup.description": "The current private beta focuses on the core Codex loop for macOS. Selected users will receive installation timing and guidance.",
    "signup.emailLabel": "Email",
    "signup.agentLabel": "Coding agent you use today",
    "signup.agentCodex": "Codex",
    "signup.agentClaude": "Claude Code",
    "signup.agentBoth": "Both",
    "signup.toolNote": "The current private beta supports Codex first.",
    "signup.submit": "Join the Mac beta ↗",
    "signup.loading": "Applying…",
    "signup.privacy": "No spam—only beta invites and important product updates.",
    "signup.error": "We couldn’t save your application. Check your email and try again.",
    "signup.successTitle": "You’re on the beta list.",
    "signup.successBody": "We’ll let you know as soon as Blabee is ready for you.",

    "footer.tagline": "Shortcut control for Codex on macOS.",
    "footer.copyright": "© 2026 Blabee",

    "metadata.title": "Blabee — One small decision. Don’t go back to the terminal.",
    "metadata.description": "Direct the next step in Codex from your Mac with one shortcut. Join the Blabee macOS private beta.",
    "metadata.socialAlt": "One small decision. Don’t go back to the terminal. Blabee for Codex on macOS.",
    "metadata.demoAria": "A demo of Blabee's 32-pixel top bar dropping open with four next actions and sending a shortcut choice back to the same agent session",
    "metadata.brandAria": "Blabee home",
    "metadata.footerBrandAria": "Back to Blabee home"
};
